# Generated by Django 4.1.3 on 2022-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=100)),
                ('username', models.CharField(max_length=20)),
                ('max_appointments', models.IntegerField()),
            ],
        ),
    ]
