# Generated by Django 4.1.3 on 2022-11-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_pharmacy', models.BooleanField(default=False)),
                ('is_insurance_firm', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False)),
                ('type_auth', models.IntegerField()),
                ('auth_id', models.IntegerField()),
                ('auth_image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('is_authorized', models.BooleanField(default=False)),
            ],
        ),
    ]
