# Generated by Django 4.1.3 on 2022-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=20)),
                ('patientName', models.CharField(max_length=20)),
                ('doctorPrice', models.IntegerField(default=100)),
                ('appointmentDate', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
